name: xyphuz_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  provider:
  qr_code_scanner:  # for scan barcode in stream
  qr_flutter: # for generate barcode
  url_launcher:
  esys_flutter_share:
  image_picker:
  firebase_ml_vision:
  intl: # for timestamp
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:

  - family: Quicksand
    fonts:
    - asset: fonts/Quicksand/Quicksand-Bold.ttf
    - asset: fonts/Quicksand/Quicksand-Light.ttf
    - asset: fonts/Quicksand/Quicksand-Medium.ttf
    - asset: fonts/Quicksand/Quicksand-Regular.ttf
    - asset: fonts/Quicksand/Quicksand-SemiBold.ttf
    - asset: fonts/Quicksand/Quicksand-VariableFont_wght.ttf
